version: '3.8'

services:
  app:
    build: ./server
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=production
      - PORT=5000
      - CLIENT_URL=http://localhost:3000
    volumes:
      - ./server:/app
      - /app/node_modules
    networks:
      - interview-network

  client:
    build: ./client
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_SERVER_URL=http://localhost:5000
    volumes:
      - ./client:/app
      - /app/node_modules
    networks:
      - interview-network
    depends_on:
      - app

networks:
  interview-network:
    driver: bridge